### ISSUE TITLE
Infinite merge pull requests on repository

### ISSUE THREAD

**Issue by dgarijo** [Autontool/auton#27]
I have a repository with a single ontology file under no folder.
Auton keeps creating pull requests with documentations in in the "docs" folder. This is what it is attempting to add in the newest commit:
docs/docs/docs/provenance/provenance/index.html

**Comment by ahmad88me** [comment]
@dgarijo The problem was that the merge request will trigger the webhook to send a request again to auton and so on so forth. I solved the problem by checking the push request is cased by a merge, if so then do nothing; otherwise continue working and generate the necessary docs, diagrams and oops for the issues
