### ISSUE TITLE
Some ontologies cannot be parsed properly

### ISSUE THREAD

**Issue by dgarijo** [Autontool/auton#34]
like http://vocab.linkeddata.es/vgo/GameOntologyv3.owl, even when they are properly specified. Maybe upgrading to Python 3 could solve this issue

**Comment by ahmad88me** [comment]
The case of the problem is that xmlrdf was using cStringIO which is only work on ASCII and the 2nd cause of the problem is xml.sax lib is using the default python encoding which is not utf-8 in python 2.7

Fixed by making the default encoding to utf-8 and using StringIO instead of cStringIO

https://github.com/Autontool/auton/commit/37a6637e41ff4b292160180d768cb2849cdc5631
